#!/bin/bash

# Check if a file is provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 IP_LIST"
    exit 1
fi

# Read each line from the file

for line in $(cat "$1")
do
    echo "creating ports list for... $line"
    $(exfiltrate "$line")
done
